/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Dardarr: typeof import('@packages/core')['default']
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const derived: typeof import('svelte/store')['derived']
  const get: typeof import('svelte/store')['get']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const hasContext: typeof import('svelte')['hasContext']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const readable: typeof import('svelte/store')['readable']
  const setContext: typeof import('svelte')['setContext']
  const tick: typeof import('svelte')['tick']
  const writable: typeof import('svelte/store')['writable']
}
