/**
 * This file was automatically generated by `scripts/generate-types.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

export {};

declare global {
  type Translation = "install_page.title" | "install_page.button";
}
