/**
 * This file was automatically generated by `scripts/generate-imports.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

import violet from "@packages/themes/violet.json";
import teal from "@packages/themes/teal.json";
import sky from "@packages/themes/sky.json";
import rose from "@packages/themes/rose.json";
import red from "@packages/themes/red.json";
import purple from "@packages/themes/purple.json";
import pink from "@packages/themes/pink.json";
import indigo from "@packages/themes/indigo.json";
import fuchsia from "@packages/themes/fuchsia.json";
import emerald from "@packages/themes/emerald.json";
import cyan from "@packages/themes/cyan.json";
import blue from "@packages/themes/blue.json";
import amber from "@packages/themes/amber.json";

export const themes = {
  violet,
  teal,
  sky,
  rose,
  red,
  purple,
  pink,
  indigo,
  fuchsia,
  emerald,
  cyan,
  blue,
  amber,
} as const;
