/**
 * This file was automatically generated by `scripts/generate-imports.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

import dardarr from "@packages/themes/dardarr.json";

export const locales = {
  dardarr,
} as const;
