/**
 * This file was automatically generated by `scripts/generate-imports.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

import fr from "@packages/locales/fr.json";
import es from "@packages/locales/es.json";
import en from "@packages/locales/en.json";
import de from "@packages/locales/de.json";

export const locales = {
  fr,
  es,
  en,
  de,
} as const;
