/**
 * This file was automatically generated by `scripts/generate-imports.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

import fr from "@packages/locales/fr.json";
import en from "@packages/locales/en.json";

export const locales = {
  fr,
  en,
} as const;
