CREATE TABLE IF NOT EXISTS Setup (
    setup_complete INTEGER PRIMARY KEY NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS System (
    id INTEGER PRIMARY KEY NOT NULL DEFAULT 1,
    locale VARCHAR(255) NOT NULL DEFAULT 'en',
    timezone VARCHAR(255) NOT NULL DEFAULT 'UTC'
);

INSERT OR REPLACE INTO System (id, locale, timezone) VALUES (1, 'en', 'UTC');

CREATE TABLE IF NOT EXISTS Config (
    id INTEGER PRIMARY KEY NOT NULL DEFAULT 1,
    name VARCHAR(255) NOT NULL,
    logo_url VARCHAR(255) NOT NULL,
    favicon_url VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Apps (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    icon_url VARCHAR(255) NOT NULL,
    internal_address VARCHAR(255) NOT NULL,
    external_address VARCHAR(255) DEFAULT NULL,
    auth_api_key VARCHAR(255) DEFAULT NULL,
    auth_username VARCHAR(255) DEFAULT NULL,
    auth_password VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    admin INTEGER NOT NULL DEFAULT 0
);
