/**
 * This file was automatically generated by `scripts/generate-schema.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

export {};

declare global {
  namespace Schema {
    /**
     * Dardarr localization schema
     */
    export interface Internationalization {
      install_page: {
        title: string;
        button: string;
      };
    }
  }
}
