/**
 * This file was automatically generated by the script `scripts/generate-json-schema-types.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

export {};

declare global {
  namespace Schema {
    /**
     * Dardarr localization schema
     */
    export interface Localization {
      install_page?: {
        title?: string;
      };
    }
  }
}
