/**
 * This file was automatically generated by the script `scripts/generate-json-schema-types.js`
 * Do not edit this file manually. Any manual changes will be overwritten.
 */

export {};

declare global {
  namespace Schema {
    /**
     * Dardarr theme schema
     */
    export interface Theme {
      /**
       * Primary color of the theme
       */
      primary_color: string;
      /**
       * Secondary color of the theme
       */
      secondary_color: string;
    }
  }
}
